### ISSUE TITLE
TypeError: Unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by FredaZero** [haosulab/ManiSkill2-Learn#6]
Hi,

I was trying to evaluate DAPG+PPO model on PickSingleYCB tasks, I followed the instructions and pass GPU id to the model and run the script. It generated the flowing information:

`PickCube-v0-eval - (run_rl.py:392) - INFO - 2023-03-02,15:53:35 - Building evaluation: eval_cfg: {'type': 'Evaluation', 'num_procs': 5, 'num': 100, 'use_hidden_state': False, 'save_traj': False, 'save_video': True, 'log_every_step': False, 'env_cfg': {'type': 'gym', 'env_name': 'PickCube-v0', 'obs_mode': 'rgbd', 'ignore_dones': False, 'control_mode': 'pd_ee_delta_pose', 'device': 'cuda:0'}}`

Then an error occur with the flowing message:

`  File "/home/keyhankouhkiloui/Shiyao/ManiSkill2/mani_skill2/envs/pick_and_place/base_env.py", line 27, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'device'`

Any suggestions? Thanks a lot

**Comment by xuanlinli17** [comment]
The error occurred due to breaking change in ManiSkill2 v0.4's renderer gpu configuration. I've fixed the issue. Please pull from the latest code.

In addition, the original pretrained models that were released (in this repo in Oct 2022) does not adapt to the current ManiSkill2 (v0.4) environments where the camera configurations were changed from when these models were trained. This causes significantly worse evaluation results. Please retrain the models yourself for now. If you are already evaluating a model you have trained, this issue will not occur.
